name: TouchySpawners
version: '${version}'
description: Mine spawners and trial spawners with Silk Touch.
author: crqzycat

main: touchy_spawners.touchySpawners.TouchySpawners
api-version: '1.21'
load: POSTWORLD
